export default [
  {
    id: 1,
    color: '#0A0E17',
    category: 'Category 1',
    subCategories: [
      'Sub Category 1',
      'Sub Category 2',
      'Sub Category 3',
      'Sub Category 4',
      'Sub Category 5',
      'Sub Category 6',
    ],
  },
  {
    id: 2,
    color: '#0A0E17',
    category: 'Category 2',
    subCategories: [
      'Sub Category 1',
      'Sub Category 2',
      'Sub Category 3',
      'Sub Category 4',
      'Sub Category 5',
      'Sub Category 6',
    ],
  },
  {
    id: 3,
    color: '#0A0E17',
    category: 'Category 3',
    subCategories: [
      'Sub Category 1',
      'Sub Category 2',
      'Sub Category 3',
      'Sub Category 4',
      'Sub Category 5',
      'Sub Category 6',
    ],
  },
  {
    id: 4,
    color: '#0A0E17',
    category: 'Category 4',
    subCategories: [
      'Sub Category 1',
      'Sub Category 2',
      'Sub Category 3',
      'Sub Category 4',
      'Sub Category 5',
      'Sub Category 6',
    ],
  },
  {
    id: 5,
    color: '#0A0E17',
    category: 'Category 5',
    subCategories: [
      'Sub Category 1',
      'Sub Category 2',
      'Sub Category 3',
      'Sub Category 4',
      'Sub Category 5',
      'Sub Category 6',
    ],
  },
  {
    id: 6,
    color: '#0A0E17',
    category: 'Category 6',
    subCategories: [
      'Sub Category 1',
      'Sub Category 2',
      'Sub Category 3',
      'Sub Category 4',
      'Sub Category 5',
      'Sub Category 6',
    ],
  },
];
